In [2]:
!pip install tensorflow
!pip install keras

In [3]:
import numpy as np
import pandas as pd
import tensorflow
from sklearn.model_selection import train_test_split
from tensorflow.python.keras.models import Sequential
from tensorflow.keras.layers import Dense, GRU, Embedding
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv("hepsiburada.csv") #csv dosyamızı okuyoruz

In [5]:
df.head(20) #csv dosyamızdaki ilk 20 satırı yazdırıyoruz

Rating                                             Review
0        1                            3 yıldır tık demedi. :)
1        1                      3 yıldır kullanıyorum müthiş 
2        1  Ürün bugün elime geçti çok fazla inceleme fırs...
3        1  Almaya karar verdim. Hemencecik geldi. Keyifle...
4        1  Günlük kullanımınızı çok çok iyi karsılıyor kı...
5        1                                        gayet güzel
6        1  Çok kaliteli bir ürün ve fiyatı da uygun. Uzun...
7        1  yaklaşık 5 senedir kullanıyorum. defalarca düş...
8        1  Ürün günlük kullanım için çok uygun. Ürünle bi...
9        1  Ürünü bir arkadaşım 2009 yılında hediye olarak...
10       1  1 gün gibi kısa bir sürede elime geçti. Ve bu ...
11       1         fiyat fayda  oranına göre çok iyi bir ürün
12       1  Güzel kullanışlı bir ürün. Herhangi bir proble...
13       1    Oyun oynamayacaklar için gayet güzel bir mouse 
14       1  Ürünü yılladır kullanıyoruz, fiyat kalite ve p...
15       1  Hoş ve kaliteli bir mouse. Leptopla kullanım i...
16       1                                    Urunu begendik 
17       1  Ürünü yorumlara bakarak aldım iyi ki de almışı...
18       1  Ürün süper kalitede değil, malzeme açısından a...
19       1  sağlam ve dayanıklı bir ürün herkese tavsiye e...

In [6]:
target= df["Rating"].values.tolist() #hedef kısım burası yani burayı tahmin edeceğiz
data= df["Review"].values.tolist()

In [7]:
x_train, x_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=21) #train ve test olarak %80 ve %20 olarak ayırıyoruz

In [8]:
x_train[500]

'ürünü yazıcıda kullanıyorum ve kalite anlamında beni gerçekten memnun ediyor baskı kalitesine çok büyük katkı sağlıyor ürünü hb farkıyla eve kadar gelmesi de ayrı bir güzellik...'

In [9]:
x_train[800]

'Çok iyi '

In [10]:
y_train[500]

1

**TOKENIZING metni modele uygun hale getirmek için kelimeleri sayılara çevirme işlemidir.**

In [11]:
num_words = 10000 #en cok kullanılan 10000 kelimeye numara atıyoruz
tokenizer = Tokenizer(num_words=num_words)
tokenizer.fit_on_texts(data)

In [12]:
tokenizer.word_index #tokenlediğimiz kelimelerin numaraları

{'çok': 1,
 'bir': 2,
 've': 3,
 'ürün': 4,
 'bu': 5,
 'iyi': 6,
 'güzel': 7,
 'için': 8,
 'tavsiye': 9,
 'ederim': 10,
 'daha': 11,
 'ama': 12,
 'da': 13,
 'gayet': 14,
 'hızlı': 15,
 'teşekkürler': 16,
 'aldım': 17,
 'de': 18,
 'ürünü': 19,
 'gibi': 20,
 'yok': 21,
 'uygun': 22,
 'olarak': 23,
 'kaliteli': 24,
 'en': 25,
 '2': 26,
 'kargo': 27,
 'fiyat': 28,
 'elime': 29,
 'kadar': 30,
 'ile': 31,
 'göre': 32,
 'geldi': 33,
 'var': 34,
 'hepsiburada': 35,
 'ben': 36,
 'gerçekten': 37,
 '1': 38,
 'fiyata': 39,
 'gün': 40,
 'sonra': 41,
 'cok': 42,
 'kesinlikle': 43,
 'telefon': 44,
 'biraz': 45,
 'hiç': 46,
 'ulaştı': 47,
 'memnun': 48,
 'hem': 49,
 'değil': 50,
 'kullanışlı': 51,
 '3': 52,
 'mükemmel': 53,
 'oldu': 54,
 'kullanıyorum': 55,
 'önce': 56,
 'sipariş': 57,
 'tek': 58,
 'her': 59,
 'bence': 60,
 'harika': 61,
 'kalitesi': 62,
 'bi': 63,
 'ayrıca': 64,
 '5': 65,
 'teşekkür': 66,
 'fiyatı': 67,
 'olması': 68,
 'ne': 69,
 'herkese': 70,
 'bile': 71,
 'uzun': 72,
 'süper': 73,

In [13]:
x_train_tokens = tokenizer.texts_to_sequences(x_train)
x_test_tokens = tokenizer.texts_to_sequences(x_test)

In [14]:
x_train[800]

'Çok iyi '

In [15]:
x_train_tokens[500]

[19,
 55,
 3,
 131,
 3133,
 278,
 37,
 48,
 165,
 1487,
 885,
 1,
 104,
 4440,
 373,
 19,
 193,
 2216,
 632,
 30,
 909,
 18,
 335,
 2,
 2023]

In [16]:
print(x_train_tokens[500])

[19, 55, 3, 131, 3133, 278, 37, 48, 165, 1487, 885, 1, 104, 4440, 373, 19, 193, 2216, 632, 30, 909, 18, 335, 2, 2023]


In [17]:
x_test_tokens[500]

[173,
 661,
 122,
 20,
 574,
 1,
 6,
 662,
 1873,
 2032,
 4779,
 5,
 4717,
 412,
 481,
 685,
 2278,
 6999,
 3,
 158,
 574,
 166,
 1895,
 98,
 516,
 470,
 968,
 4729,
 1137,
 516,
 2661,
 312,
 202]

In [18]:
num_tokens = [len(tokens) for tokens in x_train_tokens + x_test_tokens]
num_tokens = np.array(num_tokens)

In [19]:
np.mean(num_tokens) #ortalamayı buluyoruz

np.float64(20.744703220162876)

In [20]:
np.max(num_tokens) #en uzun yorumu buluyoruz

np.int64(295)

**PADDING tüm yorumların uzunluğunu eşitlemek için kullanılır; uzun olanlar kısaltılır, kısa olanların matrislerine sıfır eklenir.**

In [21]:
max_tokens = np.mean(num_tokens) + 2 * np.std(num_tokens)
max_tokens = int(max_tokens)
max_tokens #uzunları kırpmak kısaları tamamlamak için sınır belirliyoruz ve bu değer 59 index yapıypr.

59

In [22]:
x_train_pad = pad_sequences(x_train_tokens, maxlen=max_tokens)
x_test_pad = pad_sequences(x_test_tokens, maxlen=max_tokens)
x_train_pad[500] #padding işlemi sonrası bir uzatma örneği

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,   19,   55,    3,  131, 3133,  278,   37,   48,  165, 1487,
        885,    1,  104, 4440,  373,   19,  193, 2216,  632,   30,  909,
         18,  335,    2, 2023], dtype=int32)

In [23]:
np.sum(num_tokens < max_tokens) / len(num_tokens) #bize tüm yorumların yüzde kaçının belirlenen sınrıın altında olduğunu verir.

np.float64(0.9597982726686571)

In [24]:
x_train_pad = pad_sequences(x_train_tokens, maxlen=max_tokens) #kısa olanlara sıfır ekleme uzun olanları kesme işlemi
x_test_pad = pad_sequences(x_test_tokens, maxlen=max_tokens)

In [25]:
x_train_pad.shape #eğitim setindeki yorumların sayısı ve uzunluğu

(194797, 59)

In [26]:
#ÖRNEK BİR BAKIŞ
np.array(x_train_tokens[500]) #padding işlemi öncesi

array([  19,   55,    3,  131, 3133,  278,   37,   48,  165, 1487,  885,
          1,  104, 4440,  373,   19,  193, 2216,  632,   30,  909,   18,
        335,    2, 2023])

In [27]:
x_train_pad[500] #padding işlemi sonrası

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,   19,   55,    3,  131, 3133,  278,   37,   48,  165, 1487,
        885,    1,  104, 4440,  373,   19,  193, 2216,  632,   30,  909,
         18,  335,    2, 2023], dtype=int32)

In [28]:
idx = tokenizer.word_index
inverse_map = dict(zip(idx.values(), idx.keys())) #kelime numarasından tekrar kelimeye dönmek için sözlük oluşturma

In [29]:
def tokens_to_string(tokens):
    words = [inverse_map[token] for token in tokens if token!=0]
    text = ' '.join(words)
    return text
#bu fonksiyon modelin tahmin ettiği sayıları sıfırları eleyerek tekrar cümleye çevirir

In [30]:
#FONKSİYONUN ÇALIŞIP ÇALIŞMADIĞINI KONTROL ETME
tokens_to_string(x_train_tokens[500])

'ürünü kullanıyorum ve kalite anlamında beni gerçekten memnun ediyor baskı kalitesine çok büyük katkı sağlıyor ürünü hb farkıyla eve kadar gelmesi de ayrı bir güzellik'

In [31]:
x_train[500]

'ürünü yazıcıda kullanıyorum ve kalite anlamında beni gerçekten memnun ediyor baskı kalitesine çok büyük katkı sağlıyor ürünü hb farkıyla eve kadar gelmesi de ayrı bir güzellik...'

**MODEL OLUŞTURMA**

In [32]:
model = Sequential() #modeli sırayla katman katman çalıştırmak için model oluşturuyoruz

In [33]:
embedding_size = 50 #kelimeleri 50 boyutlu dizilere çevirme işlemi

In [34]:
from keras.models import Sequential
from keras.layers import Embedding

model = Sequential()
model.add(Embedding(input_dim=num_words,
                    output_dim=embedding_size,
                    input_length=max_tokens,
                    name='embedding_layer'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [35]:
model.add(GRU(units=16, return_sequences=True))
model.add(GRU(units=8, return_sequences=True))
model.add(GRU(units=4))
model.add(Dense(1, activation='sigmoid'))

In [36]:
optimizer = Adam(learning_rate=1e-3)

In [37]:
model.compile(loss='binary_crossentropy',
              optimizer=optimizer,
              metrics=['accuracy'])

In [68]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_layer (Embedding)     │ (None, 59, 50)         │       500,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ (None, 59, 16)         │         3,264 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_1 (GRU)                     │ (None, 59, 8)          │           624 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_2 (GRU)                     │ (None, 4)              │           168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,512,185 (5.77 MB)

 Trainable params: 504,061 (1.92 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,008,124 (3.85 MB)

In [44]:
print(x_train_pad.dtype)
x_train_pad = np.array(x_train_pad, dtype='int32')
x_test_pad = np.array(x_test_pad, dtype='int32')
y_train = np.array(y_train, dtype='int32')
y_test = np.array(y_test, dtype='int32')

int32


In [42]:
model.fit(x_train_pad, y_train, epochs=5, batch_size=256) #modelimizi eğitiyoruz

Epoch 1/5
761/761 ━━━━━━━━━━━━━━━━━━━━ 96s 117ms/step - accuracy: 0.9420 - loss: 0.2668
Epoch 2/5
761/761 ━━━━━━━━━━━━━━━━━━━━ 142s 117ms/step - accuracy: 0.9680 - loss: 0.1030
Epoch 3/5
761/761 ━━━━━━━━━━━━━━━━━━━━ 143s 118ms/step - accuracy: 0.9771 - loss: 0.0751
Epoch 4/5
761/761 ━━━━━━━━━━━━━━━━━━━━ 141s 118ms/step - accuracy: 0.9843 - loss: 0.0565
Epoch 5/5
761/761 ━━━━━━━━━━━━━━━━━━━━ 142s 118ms/step - accuracy: 0.9886 - loss: 0.0450


In [45]:
result = model.evaluate(x_test_pad, y_test)

1522/1522 ━━━━━━━━━━━━━━━━━━━━ 30s 19ms/step - accuracy: 0.9643 - loss: 0.1224


In [46]:
result[1]

0.9644558429718018

In [47]:
y_pred = model.predict(x=x_test_pad[0:1000])
y_pred = y_pred.T[0]

32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step


In [48]:
cls_pred = np.array([1.0 if p>0.5 else 0.0 for p in y_pred])

In [49]:
cls_true = np.array(y_test[0:1000])

In [50]:
incorrect = np.where(cls_pred != cls_true)
incorrect = incorrect[0]

In [51]:
len(incorrect)

41

In [52]:
idx = incorrect[0]
idx

np.int64(24)

In [53]:
text = x_test[idx]
text

'rahat donmuyor surtuyor sanki tavsıye etmem'

In [54]:
y_pred[idx]

np.float32(0.9687586)

In [55]:
cls_true[idx]

np.int32(0)

In [64]:
text1 = "bu ürün çok iyi herkese tavsiye ederim"
text2 = "kargo çok hızlı aynı gün elime geçti"
text3 = "büyük bir hayal kırıklığı yaşadım bu ürün bu markaya yakışmamış"
text4 = "mükemmel"
text5 = "ürün geç gelmesine rağmen beklediğimden iyi çıktı"
text6 = "hiç resimde gösterildiği gibi değil"
text7 = "kötü yorumlar gözümü korkutmuştu ancak hiçbir sorun yaşamadım teşekkürler"
text8 = "hiç bu kadar kötü bir satıcıya denk gelmemiştim ürünü geri iade ediyorum"
texts = [text1, text2, text3, text4, text5, text6, text7, text8] #modelimizde kullanacağımız yorumlar

In [65]:
tokens = tokenizer.texts_to_sequences(texts)

In [66]:
tokens_pad = pad_sequences(tokens, maxlen=max_tokens)
tokens_pad.shape

(8, 59)

In [67]:
model.predict(tokens_pad) #1 e yakın olanlar olumlu, 0 a yakın olanlar olumsuz duygu belirtir.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step


array([[0.99711084],
       [0.9915801 ],
       [0.03131621],
       [0.9968057 ],
       [0.9919335 ],
       [0.09808404],
       [0.9935678 ],
       [0.01690702]], dtype=float32)